[language-server.tsserver]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.oxlint]
command = "oxlint"
args = ["--lsp"]

[[language]]
name = "typescript"
language-servers = ["tsserver", "oxlint"]
auto-format = true
formatter = { command = "oxfmt", args = ["--stdin-filepath", "file.ts"] }

[[language]]
name = "tsx"
language-servers = ["tsserver", "oxlint"]
auto-format = true
formatter = { command = "oxfmt", args = ["--stdin-filepath", "file.tsx"] }

[[language]]
name = "javascript"
language-servers = ["tsserver", "oxlint"]
auto-format = true
formatter = { command = "oxfmt", args = ["--stdin-filepath", "file.js"] }

[[language]]
name = "jsx"
language-servers = ["tsserver", "oxlint"]
auto-format = true
formatter = { command = "oxfmt", args = ["--stdin-filepath", "file.jsx"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "oxfmt", args = ["--stdin-filepath", "file.json"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "oxfmt", args = ["--stdin-filepath", "file.md"] }
